# Generated by Django 4.2.3 on 2023-07-27 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("rollno", models.IntegerField()),
                ("department", models.CharField(max_length=20)),
                ("age", models.IntegerField()),
            ],
        ),
    ]
